version: 2.1
  
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7.10
    steps:
      - checkout
      - run:
          name: install depndancies
          command: |
            cd ../
            make install
      - run:
          name: lint code
          command: |
            cd ../
            make lint


workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
